# Generated by Django 3.0.4 on 2020-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacenero',
            options={'verbose_name': 'Almacenero', 'verbose_name_plural': 'Almaceneros'},
        ),
        migrations.AddField(
            model_name='almacenero',
            name='Prestamos_dados',
            field=models.FloatField(blank=True, null=True, verbose_name='Prestamos otorgados'),
        ),
    ]
