# Generated by Django 3.0.4 on 2020-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20200612_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenero',
            name='unidades_socios',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Unidades de Socios'),
        ),
    ]
