# Generated by Django 3.0.4 on 2020-07-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_archivosareaventas_evo_usd'),
        ('finanzas', '0003_almacenero_unidades_socios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.VentasRealizadas', verbose_name='Venta Realizada')),
            ],
            options={
                'verbose_name': 'Cuenta corriente',
                'verbose_name_plural': 'Cuentas corrientes',
            },
        ),
    ]
