# Generated by Django 3.0.4 on 2020-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_registroalmacenero_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroalmacenero',
            name='credito',
            field=models.FloatField(blank=True, null=True, verbose_name='Credito'),
        ),
        migrations.AddField(
            model_name='registroalmacenero',
            name='fdr',
            field=models.FloatField(blank=True, null=True, verbose_name='Fondos de reparo'),
        ),
        migrations.AddField(
            model_name='registroalmacenero',
            name='imprevisto',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo de imprevisto'),
        ),
        migrations.AddField(
            model_name='registroalmacenero',
            name='saldo_mat',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo de materiales'),
        ),
        migrations.AddField(
            model_name='registroalmacenero',
            name='saldo_mo',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo de mano de obra'),
        ),
    ]
