# Generated by Django 3.0.4 on 2020-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_auto_20200805_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosAdmFin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de los archivos')),
                ('resumen_credito_inv', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resumen credito inversiones')),
            ],
            options={
                'verbose_name': 'Archivo ADM/FINAN',
                'verbose_name_plural': 'Archivos ADM/FINAN',
            },
        ),
    ]
