# Generated by Django 3.0.4 on 2020-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_auto_20200928_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del arqueo')),
                ('arqueo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo Excel')),
            ],
            options={
                'verbose_name': 'Arqueo',
                'verbose_name_plural': 'Arqueos',
            },
        ),
    ]
