# Generated by Django 3.0.4 on 2020-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_arqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirodeSocios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del retiro')),
                ('monto_pesos', models.FloatField(blank=True, null=True, verbose_name='Monto en pesos')),
                ('comentario', models.CharField(blank=True, max_length=300, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
            },
        ),
    ]
