# Generated by Django 3.0.4 on 2020-11-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_auto_20200929_1454'),
        ('finanzas', '0014_retirodesocios'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirodesocios',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto'),
        ),
    ]
