# Generated by Django 3.0.4 on 2020-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_movimientoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoadmin',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='movimientoadmin',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'Espera'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ESPERA', max_length=20, verbose_name='Estado'),
        ),
    ]
