# Generated by Django 3.0.4 on 2020-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0019_auto_20201126_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cuotas', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('ventas', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('estructura_gio', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('aportes', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('socios', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('comision_venta', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('deudas', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
                ('retiro_socios', models.FloatField(blank=True, default=0, null=True, verbose_name='Cuotas a cobrar')),
            ],
            options={
                'verbose_name': 'Honorario',
                'verbose_name_plural': 'Honorarios',
            },
        ),
    ]
