# Generated by Django 3.0.4 on 2020-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0020_honorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorarios',
            name='creditos',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Retiro de socios'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='aportes',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Aportes a proyectos'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='comision_venta',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Comisión de venta'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='deudas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Deudas'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='estructura_gio',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Gastos de estructura y G.I.O'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='retiro_socios',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Retiro de socios'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='socios',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Socios'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='ventas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ventas proyectadas'),
        ),
    ]
