# Generated by Django 3.0.4 on 2020-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0022_auto_20201201_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorarios',
            name='caja_actual',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Caja actual'),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='creditos',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Creditos'),
        ),
    ]
