# Generated by Django 3.0.4 on 2020-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_auto_20201202_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroalmacenero',
            name='honorarios',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Honorarios'),
        ),
        migrations.AddField(
            model_name='registroalmacenero',
            name='retiro_socios_honorarios',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Retiro socios en honorarios'),
        ),
    ]
