# Generated by Django 3.0.4 on 2021-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0025_auto_20201217_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenero',
            name='auto_cta',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=20, verbose_name='Cuenta corriente automatica'),
        ),
    ]
