# Generated by Django 3.0.4 on 2021-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0026_almacenero_auto_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenero',
            name='inmuebles',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Inmuebles'),
        ),
        migrations.AddField(
            model_name='registroalmacenero',
            name='inmuebles',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Inmuebles'),
        ),
    ]
