# Generated by Django 3.0.4 on 2021-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0028_cuota_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='porc_boleto',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Porcentaje a aplicar boleto'),
        ),
    ]
