# Generated by Django 3.0.4 on 2021-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0029_auto_20210428_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Deposito')], max_length=20, null=True, verbose_name='Metodo'),
        ),
    ]
