# Generated by Django 3.0.4 on 2021-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0030_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
    ]
