# Generated by Django 3.0.4 on 2021-05-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0031_pago_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirodesocios',
            name='retira',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Retira'),
        ),
    ]
