# Generated by Django 3.0.4 on 2021-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0032_retirodesocios_retira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Deposito'), ('DOLARES', 'Dolares')], max_length=20, null=True, verbose_name='Metodo'),
        ),
    ]
