# Generated by Django 3.0.4 on 2021-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0033_auto_20210604_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del pago'),
        ),
    ]
