# Generated by Django 3.0.4 on 2021-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0034_auto_20210625_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='flujo',
            field=models.TextField(blank=True, null=True, verbose_name='Flujo'),
        ),
    ]
