# Generated by Django 3.0.4 on 2021-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0035_cuentacorriente_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='flujo_m3',
            field=models.TextField(blank=True, null=True, verbose_name='Flujo en M3'),
        ),
    ]
