# Generated by Django 3.1.6 on 2021-07-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0036_cuentacorriente_flujo_m3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='monto_renta_anticipada',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto fijo de renta anticipada'),
        ),
        migrations.CreateModel(
            name='PagoRentaAnticipada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del pago')),
                ('pagado', models.BooleanField(default=False)),
                ('monto_pagado', models.FloatField(default=0.0, verbose_name='Monto pagado de renta anticipada')),
                ('cuenta_corriente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.cuentacorriente', verbose_name='Cuenta corriente')),
            ],
            options={
                'verbose_name': 'Pago de renta anticipada',
                'verbose_name_plural': 'Pagos de renta anticipada',
            },
        ),
    ]
