# Generated by Django 3.2.5 on 2021-07-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0037_auto_20210706_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacorriente',
            name='monto_renta_anticipada',
        ),
        migrations.AddField(
            model_name='pagorentaanticipada',
            name='monto',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto fijo de renta anticipada'),
        ),
    ]
