# Generated by Django 3.2.5 on 2021-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0039_cuentacorriente_flujo_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='flujo_boleto',
            field=models.TextField(blank=True, null=True, verbose_name='Flujo boleto en M3'),
        ),
    ]
