# Generated by Django 3.2.5 on 2021-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0041_alter_cuentacorriente_flujo_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='flujo_boleto_m3',
            field=models.TextField(blank=True, null=True, verbose_name='Flujo boleto M3'),
        ),
    ]
