# Generated by Django 3.2.5 on 2021-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0044_cuentacorriente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono celular'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono fijo'),
        ),
    ]
