# Generated by Django 3.0.4 on 2020-05-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200420_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso_unidad', models.CharField(max_length=50, verbose_name='Piso')),
                ('nombre_unidad', models.CharField(max_length=50, verbose_name='Nomenclatura')),
                ('tipo', models.CharField(choices=[('COCHERA', 'Cochera'), ('DEPARTAMENTO', 'Departamento')], max_length=20, verbose_name='Tipo')),
                ('sup_propia', models.FloatField(verbose_name='Sup. Propia')),
                ('sup_patio', models.FloatField(blank=True, null=True, verbose_name='Sup. Patio')),
                ('sup_balcon', models.FloatField(blank=True, null=True, verbose_name='Sup. Balcon')),
                ('sup_comun', models.FloatField(verbose_name='Sup. Comun')),
                ('estado', models.CharField(choices=[('VENDIDA', 'Vendida'), ('DISPONIBLE', 'Disponible')], max_length=20, verbose_name='Estado')),
                ('asig', models.CharField(choices=[('PROYECTO', 'Proyecto'), ('HON. TERRENO', 'Hon Terreno'), ('HON. LINK', 'Hon Link')], max_length=20, verbose_name='Asignacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
