# Generated by Django 3.0.4 on 2020-05-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_unidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidades',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
    ]
