# Generated by Django 3.0.4 on 2020-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20200519_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectosTerceros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('descrip', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha_f', models.DateField(verbose_name='Fecha de entrega')),
                ('fecha_a', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
                ('m2', models.FloatField(verbose_name='Tamaño de la obra')),
            ],
            options={
                'verbose_name': 'Proyecto de tercero',
                'verbose_name_plural': 'Proyectos de terceros',
            },
        ),
    ]
