# Generated by Django 3.0.4 on 2020-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyectosterceros'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='desde',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio desde'),
        ),
    ]
