# Generated by Django 3.0.4 on 2020-06-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20200607_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='asig',
            field=models.CharField(choices=[('PROYECTO', 'Proyecto'), ('TERRENO', 'Terreno'), ('HON. LINK', 'Hon Link')], max_length=20, verbose_name='Asignacion'),
        ),
    ]
