# Generated by Django 3.0.4 on 2020-06-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_unidades_sup_equiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='tipologia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipologia'),
        ),
    ]
