# Generated by Django 3.0.4 on 2020-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_unidades_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='asig',
            field=models.CharField(choices=[('PROYECTO', 'Proyecto'), ('TERRENO', 'Terreno'), ('HON. LINK', 'Hon Link'), ('SOCIOS', 'Socios')], max_length=20, verbose_name='Asignacion'),
        ),
    ]
