# Generated by Django 3.0.4 on 2020-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20200704_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='estado',
            field=models.CharField(choices=[('VENDIDA', 'Vendida'), ('DISPONIBLE', 'Disponible'), ('SEÑADA', 'Señada')], max_length=20, verbose_name='Estado'),
        ),
    ]
