# Generated by Django 3.0.4 on 2020-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_auto_20200712_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='descuento_cochera',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento cochera'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_cocina_separada',
            field=models.FloatField(blank=True, null=True, verbose_name='Recargo cocina separada'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_frente',
            field=models.FloatField(blank=True, null=True, verbose_name='Recargo por frente'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_local',
            field=models.FloatField(blank=True, null=True, verbose_name='Recargo local'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_menor_45',
            field=models.FloatField(blank=True, null=True, verbose_name='Recargo unid. menor 45m2'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_menor_50',
            field=models.FloatField(blank=True, null=True, verbose_name='Recargo unid. menor 50m2'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_otros',
            field=models.FloatField(blank=True, null=True, verbose_name='Otros recargos'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='recargo_piso_intermedio',
            field=models.FloatField(blank=True, null=True, verbose_name='Recargo por piso intermedio'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tasa_f',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio desde'),
        ),
    ]
