# Generated by Django 3.0.4 on 2020-07-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_auto_20200719_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='tasa_f',
            field=models.FloatField(blank=True, null=True, verbose_name='Tasa de finan.'),
        ),
    ]
