# Generated by Django 3.0.4 on 2020-07-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_auto_20200723_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='folleto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Folleto'),
        ),
    ]
