# Generated by Django 3.0.4 on 2020-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_auto_20200929_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='tipo',
            field=models.CharField(choices=[('COCHERA', 'Cochera'), ('COCHERA S/D', 'Cochera Sd'), ('DEPARTAMENTO', 'Departamento'), ('LOCAL', 'Local'), ('BAULERA', 'Baulera')], max_length=20, verbose_name='Tipo'),
        ),
    ]
