# Generated by Django 3.0.4 on 2021-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_proyectos_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero de cuenta corriente'),
        ),
    ]
