# Generated by Django 3.0.4 on 2021-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_auto_20210222_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='contado',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Precio de contado'),
        ),
        migrations.AddField(
            model_name='unidades',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
    ]
