# Generated by Django 3.0.4 on 2021-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_auto_20210302_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='base',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Valor con respecto a base'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_f_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_i_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='presupuesto',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EXTRAPOLADO', 'Extrapolado'), ('BASE', 'Base')], default='EXTRAPOLADO', max_length=30, verbose_name='Estado presupuesto'),
        ),
    ]
