# Generated by Django 3.0.4 on 2021-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0026_unidades_plano_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fechas_ctas_ctes',
            field=models.TextField(blank=True, null=True, verbose_name='Fechas'),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='plano_venta',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Plano de venta'),
        ),
    ]
