# Generated by Django 3.0.4 on 2021-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0028_auto_20210625_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='flujo_ingreso_link_m3',
            field=models.TextField(blank=True, null=True, verbose_name='Fluejo de ingreso de Link M3'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='flujo_ingreso_m3',
            field=models.TextField(blank=True, null=True, verbose_name='Fluejo de ingreso M3'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='flujo_ingreso_proyecto_m3',
            field=models.TextField(blank=True, null=True, verbose_name='Fluejo de ingreso de Proyecto M3'),
        ),
    ]
