# Generated by Django 3.2.5 on 2021-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_proyeccionesproyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='google_maps',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Google Maps'),
        ),
    ]
