# Generated by Django 3.2.5 on 2021-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_proyectos_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='presupuesto',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EXTRAPOLADO', 'Extrapolado'), ('BASE', 'Base'), ('SIN_MOVIMIENTO', 'Sin Movimiento')], default='EXTRAPOLADO', max_length=30, verbose_name='Estado presupuesto'),
        ),
    ]
