# Generated by Django 3.2.5 on 2022-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0032_alter_proyectos_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='presupuesto',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EXTRAPOLADO', 'Extrapolado'), ('BASE', 'Base')], default='EXTRAPOLADO', max_length=30, verbose_name='Estado presupuesto'),
        ),
    ]
