# Generated by Django 3.2.5 on 2021-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0049_arqueochanchito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atajos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('url', models.CharField(max_length=400, verbose_name='URL')),
                ('icono', models.ImageField(upload_to='', verbose_name='Icono')),
                ('usuario', models.ManyToManyField(to='rrhh.datosusuario', verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Atajo del home',
                'verbose_name_plural': 'Atajos del home',
            },
        ),
    ]
