# Generated by Django 3.2.5 on 2022-04-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_variablesgenerales'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesgenerales',
            name='canje_activo',
            field=models.BooleanField(default=True, verbose_name='Canje activo'),
        ),
        migrations.AddField(
            model_name='variablesgenerales',
            name='linkcoins_final',
            field=models.IntegerField(default=10, verbose_name='Final de los canjes'),
        ),
        migrations.AddField(
            model_name='variablesgenerales',
            name='linkcoins_inicial',
            field=models.IntegerField(default=1, verbose_name='Inicial de los canjes'),
        ),
    ]
