# Generated by Django 3.0.4 on 2020-04-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.CharField(max_length=200, verbose_name='Nota de pedido')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre del contrato')),
                ('provee', models.CharField(max_length=200, verbose_name='Nombre del contratista')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('finish_date', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('img', models.ImageField(upload_to='proyects', verbose_name='Imagen')),
                ('presup', models.FileField(null=True, upload_to='proyects/presupuestos', verbose_name='Presupuesto')),
                ('exp', models.FileField(null=True, upload_to='proyects/exp', verbose_name='Explosión de insumos')),
                ('curva', models.FileField(null=True, upload_to='proyects/curva', verbose_name='Curva de inversión')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cer', models.IntegerField(verbose_name='Numero de certificado')),
                ('descrip', models.CharField(max_length=200, verbose_name='Descripción')),
                ('adj', models.FileField(null=True, upload_to='projects/cert', verbose_name='Adjunto')),
                ('nombre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Contratos', verbose_name='Nombre del Contrato')),
                ('obra', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Proyectos', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
