# Generated by Django 3.0.4 on 2020-05-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_auto_20200420_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingResumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha que corresponde')),
                ('precio_prom_contado', models.FloatField(verbose_name='Precio promedio contado')),
                ('precio_prom_financiado', models.FloatField(verbose_name='Precio promedio financiado')),
                ('anticipo', models.FloatField(verbose_name='Anticipo')),
                ('cuotas_pend', models.IntegerField(verbose_name='Cuotas pendientes')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Resumen de pricing',
                'verbose_name_plural': 'Resumen de pricing',
            },
        ),
    ]
