# Generated by Django 3.0.4 on 2020-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventasrealizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioMercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del estudio')),
                ('zona', models.CharField(max_length=100, verbose_name='Zona del estudio')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('proyecto', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('meses', models.IntegerField(verbose_name='Meses a la entrega')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Estudio de mercado',
                'verbose_name_plural': 'Estudios de mercado',
            },
        ),
    ]
