# Generated by Django 3.0.4 on 2020-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pricingresumen_base_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosAreaVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha que corresponde')),
                ('radiografia_cliente', models.FileField(blank=True, null=True, upload_to='', verbose_name='Radiografia del cliente')),
                ('informe_redes', models.FileField(blank=True, null=True, upload_to='', verbose_name='Informe de redes')),
                ('encuesta_postventa', models.FileField(blank=True, null=True, upload_to='', verbose_name='Encuesta de postventa')),
            ],
            options={
                'verbose_name': 'Archivos Área Ventas',
                'verbose_name_plural': 'Archivos Área Ventas',
            },
        ),
    ]
