# Generated by Django 3.0.4 on 2020-06-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_archivosareaventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='menor_45_m2',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, null=True, verbose_name='Menor a 45 m2'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='otros',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, null=True, verbose_name='Otros'),
        ),
    ]
