# Generated by Django 3.0.4 on 2020-06-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20200629_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasrealizadas',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad'),
        ),
    ]
