# Generated by Django 3.0.4 on 2020-06-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_unidades_tipologia'),
        ('ventas', '0009_auto_20200629_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasrealizadas',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Unidades', verbose_name='Unidades'),
        ),
    ]
