# Generated by Django 3.0.4 on 2020-07-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_ventasrealizadas_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosareaventas',
            name='caja_area',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Caja area'),
        ),
    ]
