# Generated by Django 3.0.4 on 2020-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_archivosareaventas_caja_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosareaventas',
            name='invest_mercado',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Investigacion de mercado'),
        ),
    ]
