# Generated by Django 3.0.4 on 2020-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_archivosareaventas_invest_mercado'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosareaventas',
            name='evo_usd',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Evolución USD/m2'),
        ),
    ]
