# Generated by Django 3.0.4 on 2020-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_archivosareaventas_evo_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosareaventas',
            name='historial_venta',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Historial de venta'),
        ),
        migrations.AddField(
            model_name='archivosareaventas',
            name='informe_venta',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Informe de venta'),
        ),
    ]
