# Generated by Django 3.0.4 on 2020-08-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_auto_20200803_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasrealizadas',
            name='precio_desde',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio desde'),
        ),
        migrations.AddField(
            model_name='ventasrealizadas',
            name='precio_pricing',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio pricing'),
        ),
    ]
