# Generated by Django 3.0.4 on 2020-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_auto_20200828_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasrealizadas',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVA', 'Activa'), ('BAJA', 'Baja')], default='ACTIVA', max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
