# Generated by Django 3.0.4 on 2020-11-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_ventasrealizadas_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoFechaEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='', verbose_name='archivo')),
            ],
            options={
                'verbose_name': 'Archivos Fecha de entrega',
                'verbose_name_plural': 'Archivos Fecha de entrega',
            },
        ),
    ]
