# Generated by Django 3.0.4 on 2020-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_auto_20201209_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasrealizadas',
            name='precio_contado',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Precio de contado'),
        ),
    ]
