# Generated by Django 3.0.4 on 2020-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_ventasrealizadas_precio_contado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasrealizadas',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email de ventas'),
        ),
    ]
