# Generated by Django 3.0.4 on 2021-01-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_comentarioscorrespondencia'),
        ('ventas', '0021_ventasrealizadas_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamosPostventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero de reclamo')),
                ('propietario', models.CharField(max_length=100, verbose_name='Propietario')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('proyecto', models.CharField(max_length=100, verbose_name='Proyecto')),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad')),
                ('fecha_reclamo', models.DateField(auto_now_add=True, verbose_name='Fecha del reclamo')),
                ('fecha_solucion', models.DateField(verbose_name='Fecha del reclamo')),
                ('estado', models.CharField(choices=[('ESPERA', 'Espera'), ('TRABAJANDO', 'Trabajando'), ('PROBLEMAS', 'Problemas'), ('LISTO', 'Listo')], default='ESPERA', max_length=40, verbose_name='Estado')),
                ('clasificacion', models.CharField(max_length=300, verbose_name='Clasificacion del problema')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Reclamo de Postventa',
                'verbose_name_plural': 'Reclamos de Postventa',
            },
        ),
    ]
