# Generated by Django 3.0.4 on 2021-01-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_reclamospostventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamospostventa',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reclamospostventa',
            name='fecha_solucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamospostventa',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
