# Generated by Django 3.0.4 on 2021-01-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_auto_20210107_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamospostventa',
            name='fecha_reclamo',
            field=models.DateField(verbose_name='Fecha del reclamo'),
        ),
    ]
