# Generated by Django 3.0.4 on 2021-03-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_auto_20210222_1134'),
        ('ventas', '0024_auto_20210130_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('inc', models.FloatField(verbose_name='Porcentaje de variación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Feature Project',
                'verbose_name_plural': 'Features Project',
            },
        ),
        migrations.CreateModel(
            name='FeaturesUni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FeaturesProjects', verbose_name='Feature')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Unidades', verbose_name='Unidades')),
            ],
            options={
                'verbose_name': 'Feature Project',
                'verbose_name_plural': 'Features Project',
            },
        ),
    ]
