# Generated by Django 3.0.4 on 2021-04-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_auto_20210302_0909'),
        ('ventas', '0025_featuresprojects_featuresuni'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosierDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha que corresponde')),
                ('adjunto', models.FileField(upload_to='', verbose_name='Adjunto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Dosier de venta',
                'verbose_name_plural': 'Dosieres de venta',
            },
        ),
    ]
