# Generated by Django 3.0.4 on 2021-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_dosierdeventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasrealizadas',
            name='precio_venta_hormigon',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Precio de venta en hormigon'),
        ),
    ]
