# Generated by Django 3.0.4 on 2021-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_ventasrealizadas_precio_venta_hormigon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientescontacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
