# Generated by Django 3.0.4 on 2021-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_clientescontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientescontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
