# Generated by Django 3.2.5 on 2021-07-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0029_auto_20210609_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientescontacto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
