# Generated by Django 3.2.5 on 2021-07-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_clientescontacto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientescontacto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='clientescontacto',
            name='imagenlogo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
