# Generated by Django 3.2.5 on 2021-07-16 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_auto_20210715_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasrealizadas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.clientescontacto', verbose_name='Cliente'),
        ),
    ]
