# Generated by Django 3.2.5 on 2021-09-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_proyeccionesproyectos'),
        ('ventas', '0032_ventasrealizadas_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgEnlacesProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=200, verbose_name='Enlaces')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Enlace de imagenes',
                'verbose_name_plural': 'Enlaces de imagenes',
            },
        ),
    ]
