# Generated by Django 3.2.5 on 2021-09-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_imgenlacesproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamospostventa',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto por responsable'),
        ),
        migrations.CreateModel(
            name='AdjuntosReclamosPostventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='', verbose_name='Adjunto')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.reclamospostventa', verbose_name='Reclamo asociado')),
            ],
            options={
                'verbose_name': 'Adjunto de reclamo',
                'verbose_name_plural': 'Adjuntos de reclamo',
            },
        ),
    ]
