# Generated by Django 3.2.5 on 2021-10-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_proyectos_google_maps'),
        ('ventas', '0035_adjuntosreclamospostventa_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del archivo')),
                ('fecha', models.DateField(verbose_name='Fecha que corresponde')),
                ('adjunto', models.FileField(upload_to='', verbose_name='Adjunto')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Archivos comercial',
                'verbose_name_plural': 'Archivos comercial',
            },
        ),
    ]
