# Generated by Django 3.2.5 on 2021-10-22 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0037_archivoscomercial_usuarios_permitidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoscomercial',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios permitidos'),
        ),
    ]
