# Generated by Django 3.2.5 on 2021-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0057_datosusuario_user'),
        ('ventas', '0038_alter_archivoscomercial_usuarios_permitidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoscomercial',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, to='rrhh.datosusuario', verbose_name='Usuarios permitidos'),
        ),
    ]
