# Generated by Django 3.2.5 on 2021-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_alter_archivoscomercial_usuarios_permitidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionReclamosPostventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Clasificacion del problema')),
            ],
            options={
                'verbose_name': 'Clasificacion del reclamo',
                'verbose_name_plural': 'Clasificaciones de los reclamos',
            },
        ),
    ]
