# Generated by Django 3.2.5 on 2021-11-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_clasificacionreclamospostventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionreclamospostventa',
            name='nombre',
            field=models.CharField(max_length=300, unique=True, verbose_name='Clasificacion del problema'),
        ),
    ]
