# Generated by Django 3.2.5 on 2021-11-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0041_alter_clasificacionreclamospostventa_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioSolucionPostventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del formulario')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('metodo_pago', models.CharField(max_length=100, verbose_name='Metodo de pago')),
                ('costo_mo', models.FloatField(verbose_name='Costo de MO')),
                ('costo_mat', models.FloatField(verbose_name='Costo de materiales')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.reclamospostventa', verbose_name='Reclamo asociado')),
            ],
            options={
                'verbose_name': 'Formulario de solución de postventa',
                'verbose_name_plural': 'Formularios de solución de postventa',
            },
        ),
        migrations.CreateModel(
            name='FormularioDetallePostventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.reclamospostventa', verbose_name='Reclamo asociado')),
            ],
            options={
                'verbose_name': 'Formulario de detalle de postventa',
                'verbose_name_plural': 'Formularios de detalles de postventa',
            },
        ),
    ]
