# Generated by Django 3.2.5 on 2021-11-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_formulariodetallepostventa_formulariosolucionpostventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulariodetallepostventa',
            old_name='fecha_incio',
            new_name='fecha_inicio',
        ),
    ]
