# Generated by Django 3.2.5 on 2021-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0043_rename_fecha_incio_formulariodetallepostventa_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosolucionpostventa',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del formulario'),
        ),
    ]
