# Generated by Django 3.0.4 on 2020-05-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0012_modelopresupuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inv', models.CharField(max_length=200, verbose_name='Numero Inventario')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('amortizacion', models.IntegerField(verbose_name='Amortización (años)')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Articulos', verbose_name='Articulo')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
    ]
