# Generated by Django 3.0.4 on 2020-11-11 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0020_auto_20201111_0942'),
        ('sigma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción de la tarea')),
                ('unidad', models.CharField(max_length=200, verbose_name='Unidad')),
                ('rend', models.FloatField(blank=True, null=True, verbose_name='Rendimiento esperado (hs/unidad)')),
                ('vinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Articulos', verbose_name='Articulo')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la subtarea')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción de la tarea')),
                ('unidad', models.CharField(max_length=200, verbose_name='Unidad')),
                ('rend', models.FloatField(blank=True, null=True, verbose_name='Rendimiento esperado (hs/unidad)')),
                ('vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.Tarea', verbose_name='Tarea madre')),
            ],
            options={
                'verbose_name': 'Sub tarea',
                'verbose_name_plural': 'Sub tareas',
            },
        ),
    ]
