# Generated by Django 3.0.4 on 2020-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0002_subtarea_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(verbose_name='DNI del operario')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del operario')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('NO ACTIVO', 'No Activo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
            },
        ),
    ]
