# Generated by Django 3.0.4 on 2020-11-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigma', '0003_operario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partediario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider', models.CharField(max_length=200, verbose_name='Nombre del lider de cuadrilla')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del parte')),
                ('horas', models.FloatField(blank=True, null=True, verbose_name='Horas')),
                ('avance', models.FloatField(blank=True, null=True, verbose_name='Avance')),
                ('subtarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.SubTarea', verbose_name='Subtarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.Operario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Parte diario',
                'verbose_name_plural': 'Partes diarios',
            },
        ),
    ]
