# Generated by Django 3.2.5 on 2021-11-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0032_auto_20211124_1450'),
        ('sigma', '0004_partediario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AddField(
            model_name='inventario',
            name='constante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.constantes'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_md',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio en moneda dura'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_compra',
            field=models.DateField(verbose_name='Fecha de compra'),
        ),
    ]
