# Generated by Django 3.2.5 on 2022-02-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0038_presupuestos_consumption_details'),
        ('sigma', '0005_auto_20211129_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_inventario', to='presupuestos.articulos', verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='num_inv',
            field=models.CharField(max_length=200, unique=True, verbose_name='Numero Inventario'),
        ),
    ]
