# Generated by Django 3.1.6 on 2021-09-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0031_documentacionproyectopresupuesto'),
        ('proyectos', '0031_proyectos_google_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidasCapitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.capitulos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
            },
        ),
        migrations.CreateModel(
            name='SubPartidasCapitulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curvas.partidascapitulos')),
            ],
            options={
                'verbose_name': 'Subpartida',
                'verbose_name_plural': 'Subpartidas',
            },
        ),
        migrations.CreateModel(
            name='ComposicionesSubpartidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.articulos')),
                ('subpartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curvas.subpartidascapitulos')),
            ],
            options={
                'verbose_name': 'Composicion',
                'verbose_name_plural': 'Composiciones',
            },
        ),
    ]
