# Generated by Django 3.2.5 on 2021-09-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidascapitulos',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
    ]
