# Generated by Django 3.2.5 on 2021-10-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curvas', '0003_auto_20210930_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidascapitulos',
            options={'verbose_name': 'Contenedor', 'verbose_name_plural': 'Contenedores'},
        ),
    ]
