# Generated by Django 3.2.5 on 2021-10-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curvas', '0004_alter_partidascapitulos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidascapitulos',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
    ]
