# Generated by Django 3.0.4 on 2020-04-13 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaRubros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del rubro')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Tipologias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('un', models.CharField(max_length=200, verbose_name='Unidad')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computos.ListaRubros', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Tipologia',
                'verbose_name_plural': 'Tipologias',
            },
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='Computos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_lleno', models.FloatField(verbose_name='Valor lleno')),
                ('valor_vacio', models.FloatField(verbose_name='Valor vacio')),
                ('valor_total', models.FloatField(verbose_name='Valor total')),
                ('valor_obra', models.FloatField(blank=True, verbose_name='Valor en obra')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computos.Plantas', verbose_name='Planta')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computos.ListaRubros', verbose_name='Rubro')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computos.Tipologias', verbose_name='Tipologia')),
            ],
            options={
                'verbose_name': 'Computo',
                'verbose_name_plural': 'Computos',
            },
        ),
    ]
