# Generated by Django 3.0.4 on 2020-04-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computos',
            name='valor_lleno',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor lleno'),
        ),
        migrations.AlterField(
            model_name='computos',
            name='valor_obra',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor en obra'),
        ),
        migrations.AlterField(
            model_name='computos',
            name='valor_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='computos',
            name='valor_vacio',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor vacio'),
        ),
    ]
