# Generated by Django 3.0.4 on 2020-04-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computos', '0002_auto_20200413_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='computos',
            name='fecha_a',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
