# Generated by Django 3.0.4 on 2020-04-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computos', '0003_computos_fecha_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantas',
            name='proyecto',
        ),
    ]
