# Generated by Django 3.0.4 on 2020-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor del proyecto')),
                ('fecha_a', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyectos')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='DatosProyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_a', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('img', models.ImageField(upload_to='proyects', verbose_name='Imagen')),
                ('presup', models.FileField(null=True, upload_to='proyects/presupuestos', verbose_name='Presupuesto')),
                ('exp', models.FileField(null=True, upload_to='proyects/exp', verbose_name='Explosión de insumos')),
                ('curva', models.FileField(null=True, upload_to='proyects/curva', verbose_name='Curva de inversión')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Dato de proyecto',
                'verbose_name_plural': 'Datos de proyectos',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('valor_aux', models.FloatField(null=True)),
                ('descrip', models.TextField()),
                ('unidad', models.CharField(blank=True, max_length=10)),
                ('fecha_c', models.DateField(auto_now_add=True)),
                ('fecha_a', models.DateField(auto_now=True)),
                ('constante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Constantes')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
