# Generated by Django 3.0.4 on 2020-04-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constantes',
            options={'verbose_name': 'Constante', 'verbose_name_plural': 'Constantes'},
        ),
        migrations.CreateModel(
            name='Prametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_des_p', models.FloatField(verbose_name='Tasa de descuento del costo')),
                ('soft', models.FloatField(verbose_name='Soft + IVA')),
                ('imprevitso', models.FloatField(verbose_name='Imprevisto')),
                ('terreno', models.FloatField(verbose_name='Honorarios Terreno')),
                ('link', models.FloatField(verbose_name='Honorarios Desarrolladora')),
                ('comer', models.FloatField(verbose_name='Honorarios Comercialización')),
                ('por_comer', models.FloatField(verbose_name='Porcentaje aplicación comercialización')),
                ('tem_iibb', models.FloatField(verbose_name='TEM e IIBB')),
                ('por_temiibb', models.FloatField(verbose_name='Porcentaje de aplicación TEM e IIBB')),
                ('ganancia', models.FloatField(verbose_name='Ganancia')),
                ('tasa_des', models.FloatField(verbose_name='Tasa descuento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyectos')),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
            },
        ),
    ]
