# Generated by Django 3.0.4 on 2020-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='desde',
            name='fecha_c',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha del informe'),
        ),
    ]
