# Generated by Django 3.0.4 on 2020-04-14 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_desde_fecha_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='desde',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Presupuestos', verbose_name='Parametros'),
        ),
        migrations.AlterField(
            model_name='desde',
            name='fecha_c',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha del informe'),
        ),
    ]
