# Generated by Django 3.0.4 on 2020-04-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_auto_20200414_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desde',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Presupuestos', verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='valor',
            field=models.FloatField(verbose_name='Valor del proyecto'),
        ),
    ]
