# Generated by Django 3.0.4 on 2020-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_auto_20200415_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantes',
            name='fecha_a',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
