# Generated by Django 3.0.4 on 2020-04-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_constantes_fecha_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='desde',
            name='pricing',
            field=models.FloatField(blank=True, null=True, verbose_name='Pricing'),
        ),
    ]
