# Generated by Django 3.0.4 on 2020-04-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0009_articulos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.IntegerField(auto_created=True)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('unidad', models.CharField(max_length=10, verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Analisis',
                'verbose_name_plural': 'Analisis',
            },
        ),
        migrations.CreateModel(
            name='CompoAnalisis',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Analisis', verbose_name='Analisis')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Articulos', verbose_name='Articulo')),
            ],
            options={
                'verbose_name': 'Composición',
                'verbose_name_plural': 'Composición',
            },
        ),
    ]
