# Generated by Django 3.0.4 on 2020-04-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200420_1150'),
        ('computos', '0004_remove_plantas_proyecto'),
        ('presupuestos', '0011_capitulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelopresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True, verbose_name='Cantidad')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Analisis', verbose_name='Analisis')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Capitulos', verbose_name='Capitulo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
                ('vinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='computos.Tipologias', verbose_name='Vinculación')),
            ],
            options={
                'verbose_name': 'Modelo presupuesto',
                'verbose_name_plural': 'Modelo presupuestos',
            },
        ),
    ]
