# Generated by Django 3.0.4 on 2020-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0012_modelopresupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='imprevisto',
            field=models.FloatField(blank=True, null=True, verbose_name='Saldo del imprevisto'),
        ),
    ]
