# Generated by Django 3.0.4 on 2020-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0014_auto_20200611_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='anticipos',
            field=models.FloatField(blank=True, null=True, verbose_name='Anticipos'),
        ),
    ]
