# Generated by Django 3.0.4 on 2020-08-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0017_presupuestos_saldo_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrodeconstantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('constante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Constantes', verbose_name='Constante')),
            ],
            options={
                'verbose_name': 'Registro de contantes ultimo',
                'verbose_name_plural': 'Registros de constantes ultimo',
            },
        ),
    ]
