# Generated by Django 3.0.4 on 2020-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0018_registrodeconstantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='presupuestador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Presupuestador'),
        ),
    ]
