# Generated by Django 3.0.4 on 2020-11-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0019_presupuestos_presupuestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeconstantes',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registrodeconstantes',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
