# Generated by Django 3.0.4 on 2020-11-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_auto_20200929_1454'),
        ('presupuestos', '0020_auto_20201111_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcentajeCapitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(verbose_name='Porcentaje')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Capitulos', verbose_name='Capitulo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Incidencia del capitulo',
                'verbose_name_plural': 'incidencia del capitulo',
            },
        ),
    ]
