# Generated by Django 3.0.4 on 2021-01-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_anuncios'),
        ('proyectos', '0020_proyectos_imagen'),
        ('presupuestos', '0021_porcentajecapitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del informe')),
                ('informe', models.TextField(blank=True, null=True, verbose_name='Descripción de la causa')),
                ('devolucion', models.TextField(blank=True, null=True, verbose_name='Devolución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Capitulo')),
            ],
            options={
                'verbose_name': 'Informe mensual',
                'verbose_name_plural': 'Informes mensuales',
            },
        ),
        migrations.CreateModel(
            name='TareasProgramadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=200, verbose_name='Tareas programadas')),
                ('estado', models.CharField(choices=[('LISTO', 'Listo'), ('TRABAJANDO', 'Trabajando'), ('ESPERA', 'Espera'), ('PROBLEMAS', 'Problemas')], max_length=20, verbose_name='Estado de las tareas')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.InformeMensual', verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='Bitacoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha del informe')),
                ('informe', models.TextField(verbose_name='Descripción de la causa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
    ]
