# Generated by Django 3.0.4 on 2021-02-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0022_bitacoras_informemensual_tareasprogramadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoras',
            name='descrip',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la causa'),
        ),
        migrations.AddField(
            model_name='bitacoras',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='bitacoras',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.InformeMensual', verbose_name='Informe'),
        ),
    ]
