# Generated by Django 3.0.4 on 2021-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0023_auto_20210208_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopresupuesto',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='modelopresupuesto',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
    ]
