# Generated by Django 3.0.4 on 2021-05-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0025_presupuestosalmacenados'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantes',
            name='cuenta_corriente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
