# Generated by Django 3.2.5 on 2021-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0026_constantes_cuenta_corriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='tipo_articulo',
            field=models.CharField(blank=True, choices=[('MATERIAL', 'Material'), ('SUBCONTRATO', 'Subcontrato'), ('MO', 'Mo')], max_length=20, null=True, verbose_name='Estado de las tareas'),
        ),
    ]
