# Generated by Django 3.2.5 on 2021-07-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0029_auto_20210625_1446'),
        ('presupuestos', '0028_auto_20210730_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='prametros',
            name='proyecto_no_est',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proyecto no estructurado'),
        ),
        migrations.AlterField(
            model_name='prametros',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyectos'),
        ),
    ]
