# Generated by Django 3.2.5 on 2021-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0029_auto_20210730_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='prametros',
            name='depto',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Proporción depto'),
        ),
    ]
