# Generated by Django 3.2.5 on 2021-09-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_proyeccionesproyectos'),
        ('presupuestos', '0030_prametros_depto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionProyectoPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=200, verbose_name='Descripción')),
                ('entregado', models.BooleanField(verbose_name='Entregado')),
                ('cuantificado', models.BooleanField(verbose_name='Cuantificado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Check-list-Documentacion',
                'verbose_name_plural': 'Check-list-Documentacion',
            },
        ),
    ]
