# Generated by Django 3.2.5 on 2021-11-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_proyectos_google_maps'),
        ('presupuestos', '0031_documentacionproyectopresupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='proyecto_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_base', to='proyectos.proyectos', verbose_name='Proyecto base'),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyectos.proyectos', verbose_name='Proyectos'),
        ),
    ]
