# Generated by Django 3.2.5 on 2021-12-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0033_bitacoras_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareasprogramadas',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cumplimiento'),
        ),
    ]
