# Generated by Django 3.2.5 on 2021-12-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0032_alter_proyectos_presupuesto'),
        ('presupuestos', '0034_tareasprogramadas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareasprogramadas',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='tareasprogramadas',
            name='estado',
            field=models.CharField(choices=[('LISTO', 'Listo'), ('TRABAJANDO', 'Trabajando'), ('ESPERA', 'Espera'), ('PROBLEMAS', 'Problemas')], default='ESPERA', max_length=20, verbose_name='Estado de las tareas'),
        ),
    ]
