# Generated by Django 3.2.5 on 2021-12-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0035_auto_20211224_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareasprogramadas',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuestos.informemensual', verbose_name='Informe'),
        ),
    ]
