# Generated by Django 3.2.5 on 2022-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0036_alter_tareasprogramadas_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='balance_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del saldo'),
        ),
        migrations.AlterField(
            model_name='tareasprogramadas',
            name='fecha',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de cumplimiento'),
        ),
    ]
