# Generated by Django 3.2.5 on 2022-01-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0037_auto_20220108_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='consumption_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del consumo'),
        ),
    ]
