# Generated by Django 3.0.4 on 2020-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=200, verbose_name='Identificacion')),
                ('imagen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Dato de usuario',
                'verbose_name_plural': 'Datos de los usuarios',
            },
        ),
    ]
