# Generated by Django 3.0.4 on 2020-10-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_auto_20201029_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajesgenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje general',
                'verbose_name_plural': 'Mensajes generales',
            },
        ),
    ]
