# Generated by Django 3.0.4 on 2020-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_mensajesgenerales'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='cumpleaños',
            field=models.DateField(blank=True, null=True, verbose_name='Cumple'),
        ),
    ]
