# Generated by Django 3.0.4 on 2020-11-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_auto_20200929_1454'),
        ('rrhh', '0003_mensajesgenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nota de pedido numero')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo de la nota de pedido')),
                ('creador', models.CharField(max_length=200, verbose_name='Creador')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualiacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha_requerida', models.CharField(max_length=200, verbose_name='Creador')),
                ('copia', models.CharField(max_length=200, verbose_name='Quien recibe en copia')),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjuntos')),
                ('envio_documentacion', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, verbose_name='Es para enviar documentación')),
                ('cambio_proyecto', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, verbose_name='Genera cambios al proyecto')),
                ('comunicacion_general', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, verbose_name='Es comunicación general')),
                ('descripcion', models.TextField(verbose_name='Descripción de la causa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Nota de pedido',
                'verbose_name_plural': 'Notas de pedido',
            },
        ),
    ]
