# Generated by Django 3.0.4 on 2020-11-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_datosusuario_cumpleaños'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosusuario',
            old_name='cumpleaños',
            new_name='cumplea',
        ),
    ]
