# Generated by Django 3.0.4 on 2020-11-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_auto_20201105_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosusuario',
            name='cumplea',
        ),
    ]
