# Generated by Django 3.0.4 on 2020-12-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_auto_20201106_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
