# Generated by Django 3.0.4 on 2020-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_datosusuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('NO ACTIVO', 'No Activo')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
    ]
