# Generated by Django 3.0.4 on 2021-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_vacaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_final',
            field=models.DateField(verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
