# Generated by Django 3.0.4 on 2021-01-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_auto_20210106_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosCorrespondencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200, verbose_name='Creador')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.NotaDePedido', verbose_name='Usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
