# Generated by Django 3.0.4 on 2021-01-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_comentarioscorrespondencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonedaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la moneda')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de moneda')),
                ('usuario_portador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario Portador')),
            ],
            options={
                'verbose_name': 'Moneda link',
                'verbose_name_plural': 'Monedas link',
            },
        ),
        migrations.CreateModel(
            name='EntregaMoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la entrega')),
                ('mensaje', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mensaje de la entrega')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.MonedaLink', verbose_name='Usuario Portador')),
                ('usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario Recibe')),
            ],
            options={
                'verbose_name': 'Entrega de moneda',
                'verbose_name_plural': 'Entregas de monedas',
            },
        ),
    ]
