# Generated by Django 3.0.4 on 2021-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_entregamoneda_monedalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedalink',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
