# Generated by Django 3.0.4 on 2021-02-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_proyectos_imagen'),
        ('rrhh', '0016_anuncios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden de la tarea')),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('estado', models.CharField(choices=[('ESPERA', 'Espera'), ('TRABAJANDO', 'Trabajando'), ('PROBLEMAS', 'Problemas'), ('LISTO', 'Listo')], default='ESPERA', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjunto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
    ]
