# Generated by Django 3.0.4 on 2021-02-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0017_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='area',
            field=models.CharField(choices=[('PRESUPUESTOS', 'Presupuesto'), ('COMPRAS Y CONTRATACIONES', 'Compras Contrataciones'), ('EQUIPO TECNICO', 'Equipo Tecnico'), ('ADMINISTRACIÓN Y FINANZAS', 'Administracion Finanzas'), ('COMERCIALIZACIÓN Y MARKETING', 'Comercializacion Marketing'), ('RECURSOS HUMANOS', 'Rr Hh'), ('DIRECCIÓN', 'Direccion')], max_length=100, verbose_name='Area'),
        ),
    ]
