# Generated by Django 3.0.4 on 2021-02-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0019_auto_20210205_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la minuta')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('integrantes', models.CharField(max_length=200, verbose_name='Integrantes')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Minuta',
                'verbose_name_plural': 'Minutas',
            },
        ),
        migrations.CreateModel(
            name='Acuerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=400, verbose_name='Tema/acuerdo')),
                ('minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.Minutas', verbose_name='Minutas')),
            ],
            options={
                'verbose_name': 'Acuerdo',
                'verbose_name_plural': 'Acuerdos',
            },
        ),
    ]
