# Generated by Django 3.0.4 on 2021-02-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0020_acuerdos_minutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdos',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Responsable'),
        ),
    ]
