# Generated by Django 3.0.4 on 2021-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0021_acuerdos_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdos',
            name='estado',
            field=models.CharField(choices=[('CHECK', 'Check'), ('NO CHECK', 'No Check')], default='NO CHECK', max_length=20, verbose_name='Estado'),
        ),
    ]
