# Generated by Django 3.0.4 on 2021-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0023_acuerdos_fecha_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiosMonedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del premio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de monedas')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
            },
        ),
        migrations.AddField(
            model_name='monedalink',
            name='activo',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=20, verbose_name='Activo'),
        ),
    ]
