# Generated by Django 3.0.4 on 2021-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0024_auto_20210226_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Identificacion'),
        ),
    ]
