# Generated by Django 3.0.4 on 2021-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0026_logros'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
