# Generated by Django 3.0.4 on 2021-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0028_auto_20210323_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='Comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='Telefono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='datosusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
