# Generated by Django 3.0.4 on 2021-03-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0029_auto_20210324_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('INGRESOS', 'Ingresos'), ('GASTOS', 'Gastos')], default='INGRESOS', max_length=20, verbose_name='Ingreso o gasto')),
                ('cuenta', models.CharField(max_length=400, verbose_name='Cuenta')),
                ('categoria', models.CharField(max_length=400, verbose_name='Categoria')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('nota', models.CharField(max_length=400, verbose_name='Nota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
