# Generated by Django 3.0.4 on 2021-03-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0030_registrocontable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjunto'),
        ),
    ]
