# Generated by Django 3.0.4 on 2021-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0031_registrocontable_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutas',
            name='reunion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reunión'),
        ),
    ]
