# Generated by Django 3.0.4 on 2021-04-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0032_minutas_reunion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanjeMonedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('premio', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre del premio')),
                ('monedas', models.IntegerField(verbose_name='Monedas ocupadas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Canje de moneda',
                'verbose_name_plural': 'Canje de monedas',
            },
        ),
    ]
