# Generated by Django 3.0.4 on 2021-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0034_premiosmonedas_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregamoneda',
            name='entregado',
            field=models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], default='NO', max_length=20, verbose_name='Entregado'),
        ),
    ]
