# Generated by Django 3.0.4 on 2021-05-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0036_canjemonedas_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('ESPERA', 'Espera'), ('LISTO', 'Listo'), ('DESCARTADO', 'Descartado')], default='ESPERA', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjunto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
            },
        ),
    ]
