# Generated by Django 3.0.4 on 2021-05-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0037_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='fecha_listo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
