# Generated by Django 3.0.4 on 2021-06-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0039_auto_20210512_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicRegistroContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(max_length=400, verbose_name='Entrada')),
                ('salida', models.CharField(max_length=400, verbose_name='Salida')),
            ],
        ),
        migrations.AddField(
            model_name='registrocontable',
            name='codigo',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Codigo'),
        ),
    ]
