# Generated by Django 3.0.4 on 2021-06-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0041_auto_20210604_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicregistrocontable',
            options={'verbose_name': 'Diccionario registro', 'verbose_name_plural': 'Diccionario registros'},
        ),
    ]
