# Generated by Django 3.0.4 on 2021-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0042_auto_20210609_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atajos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('url', models.CharField(max_length=400, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Atajo',
                'verbose_name_plural': 'Atajos',
            },
        ),
    ]
