# Generated by Django 3.0.4 on 2021-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0043_atajos'),
    ]

    operations = [
        migrations.AddField(
            model_name='atajos',
            name='icon',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ICONO'),
        ),
        migrations.AlterField(
            model_name='atajos',
            name='url',
            field=models.CharField(max_length=400, verbose_name='URL'),
        ),
    ]
