# Generated by Django 3.0.4 on 2021-06-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0029_auto_20210625_1446'),
        ('rrhh', '0044_auto_20210630_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto que sigue'),
        ),
    ]
