# Generated by Django 3.2.5 on 2021-07-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0045_datosusuario_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosEmpresariales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo de la nota de pedido')),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjuntos')),
                ('fecha_actualiacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Documentación empresarial',
                'verbose_name_plural': 'Documentos de la empresa',
            },
        ),
    ]
