# Generated by Django 3.2.5 on 2021-07-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0046_documentosempresariales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentosEmpresariales',
        ),
    ]
