# Generated by Django 3.2.5 on 2021-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0047_delete_documentosempresariales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('descrip', models.CharField(max_length=600, verbose_name='Descripción')),
                ('adjunto', models.FileField(upload_to='', verbose_name='Adjunto')),
            ],
            options={
                'verbose_name': 'Archivos',
                'verbose_name_plural': 'Archivos generales',
            },
        ),
    ]
