# Generated by Django 3.2.5 on 2021-07-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0048_archivosgenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoChanchito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.CharField(max_length=400, verbose_name='Caja')),
                ('arqueo', models.CharField(max_length=400, verbose_name='Arqueo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Arqueo de chanchito',
                'verbose_name_plural': 'Arqueos de chanchito',
            },
        ),
    ]
