# Generated by Django 3.2.5 on 2021-08-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0049_arqueochanchito'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusuario',
            name='tutorial',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=20, null=True, verbose_name='Tutorial'),
        ),
        migrations.AlterField(
            model_name='datosusuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('NO ACTIVO', 'No')], default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
    ]
