# Generated by Django 3.2.5 on 2021-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0051_sugerencia_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='importe_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Importe USD'),
        ),
    ]
