# Generated by Django 3.2.5 on 2021-09-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0052_registrocontable_importe_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('pagado', models.BooleanField(verbose_name='Pagado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto personal',
                'verbose_name_plural': 'Presupuestos personal',
            },
        ),
    ]
