# Generated by Django 3.2.5 on 2021-09-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0053_presupuestopersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
                ('usuarios_visibles', models.ManyToManyField(related_name='Visibilidad', to='rrhh.datosusuario', verbose_name='Usuario visibles')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.AddField(
            model_name='registrocontable',
            name='caja_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.cajas', verbose_name='Caja vinculada'),
        ),
    ]
