# Generated by Django 3.2.5 on 2021-09-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0054_auto_20210913_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='usuarios_visibles',
            field=models.ManyToManyField(blank=True, null=True, related_name='Visibilidad', to='rrhh.datosusuario', verbose_name='Usuario visibles'),
        ),
    ]
