# Generated by Django 3.2.5 on 2021-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0055_alter_cajas_usuarios_visibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajas',
            name='usuarios_visibles',
            field=models.ManyToManyField(blank=True, related_name='Visibilidad', to='rrhh.datosusuario', verbose_name='Usuario visibles'),
        ),
    ]
