# Generated by Django 3.2.5 on 2021-07-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0048_archivosgenerales'),
        ('ventas', '0030_clientescontacto_activo'),
        ('proyectos', '0029_auto_20210625_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la consulta')),
                ('medio_contacto', models.CharField(max_length=50, verbose_name='Medio de contacto')),
                ('tipologia', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clientescontacto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
                ('tipologia2', models.ManyToManyField(blank=True, null=True, to='crm.Tipologia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario')),
            ],
            options={
                'verbose_name': 'Consulta de cliente',
                'verbose_name_plural': 'Consultas de clientes',
            },
        ),
    ]
