# Generated by Django 3.2.5 on 2021-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='adjunto_propuesta',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Propuesta'),
        ),
    ]
