# Generated by Django 3.2.5 on 2021-08-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210716_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipologia2',
            field=models.ManyToManyField(blank=True, to='crm.Tipologia'),
        ),
    ]
