# Generated by Django 3.0.4 on 2020-12-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0007_datosusuario_email'),
        ('proyectos', '0017_auto_20200929_1454'),
        ('compras', '0021_auto_20201215_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la etapa')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='ItemEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la subetapa')),
                ('estado', models.CharField(choices=[('ESPERA', 'Espera'), ('TRABAJANDO', 'Trabajando'), ('PROBLEMAS', 'Problemas'), ('LISTO', 'Listo')], default='ESPERA', editable=False, max_length=20, verbose_name='Estado')),
                ('archivo_vigente', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo vigente')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Contratos', verbose_name='Contrato')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnica.Etapas', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Sub etapa',
                'verbose_name_plural': 'Sub etapas',
            },
        ),
    ]
