# Generated by Django 3.0.4 on 2020-12-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemetapa',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'Espera'), ('TRABAJANDO', 'Trabajando'), ('PROBLEMAS', 'Problemas'), ('LISTO', 'Listo')], default='ESPERA', max_length=20, verbose_name='Estado'),
        ),
    ]
