# Generated by Django 3.0.4 on 2020-12-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0003_tecnicamensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemetapa',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de finalziación'),
        ),
        migrations.AddField(
            model_name='itemetapa',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AddField(
            model_name='itemetapa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
