# Generated by Django 3.0.4 on 2020-12-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0004_auto_20201223_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemetapa',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL del servidor'),
        ),
    ]
