# Generated by Django 3.0.4 on 2020-12-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0005_itemetapa_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemetapa',
            old_name='fecha_estimada',
            new_name='fecha_estimada_f',
        ),
        migrations.AddField(
            model_name='itemetapa',
            name='fecha_estimada_i',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de iniciación'),
        ),
        migrations.AddField(
            model_name='itemetapa',
            name='orden',
            field=models.FloatField(default=0.0, verbose_name='Orden'),
        ),
    ]
