# Generated by Django 3.0.4 on 2021-01-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_proyectos_fecha_i'),
        ('rrhh', '0015_auto_20210108_1258'),
        ('tecnica', '0008_subsubitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Lider de proyecto',
                'verbose_name_plural': 'Lideres de proyectos',
            },
        ),
    ]
