# Generated by Django 3.0.4 on 2021-04-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0032_minutas_reunion'),
        ('proyectos', '0023_auto_20210302_0909'),
        ('tecnica', '0009_lp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDesvios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del desvio')),
                ('descrip', models.TextField(verbose_name='Descripción')),
                ('dias', models.IntegerField(verbose_name='Dias de desvios')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjunto')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Registro de desvio',
                'verbose_name_plural': 'Registros de desvios',
            },
        ),
    ]
