# Generated by Django 3.0.4 on 2021-04-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_auto_20210302_0909'),
        ('presupuestos', '0025_presupuestosalmacenados'),
        ('tecnica', '0010_registrodesvios'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenPlanificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_i', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_f', models.DateField(blank=True, null=True, verbose_name='Fecha final')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Capitulos', verbose_name='Capitulo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Gerencia planif',
                'verbose_name_plural': 'Gerencia planif',
            },
        ),
    ]
