# Generated by Django 3.0.4 on 2020-04-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('age', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descrip', models.TextField(verbose_name='Descripción')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('update', models.DateField(auto_now=True, verbose_name='Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='StockComprasAnticipadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='age.Agenda')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Proyectos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedores')),
            ],
            options={
                'verbose_name': 'Stock compra anticipada',
                'verbose_name_plural': 'Stock compras anticipadas',
            },
        ),
    ]
