# Generated by Django 3.0.4 on 2020-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descrip', models.TextField(verbose_name='Descripción')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('update', models.DateField(auto_now=True, verbose_name='Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='StockComprasAnticipadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Articulos')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedores')),
            ],
            options={
                'verbose_name': 'Stock compra anticipada',
                'verbose_name_plural': 'Stock compras anticipadas',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('np', models.CharField(max_length=200, verbose_name='Nota de pedido')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del contrato')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedores', verbose_name='Nombre del contratista')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cer', models.IntegerField(verbose_name='Numero de certificado')),
                ('descrip', models.CharField(max_length=200, verbose_name='Descripción')),
                ('adj', models.FileField(null=True, upload_to='projects/cert', verbose_name='Adjunto')),
                ('contrato', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Contratos', verbose_name='Nombre del Contrato')),
                ('proyecto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
