# Generated by Django 3.0.4 on 2020-04-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_auto_20200415_0839'),
        ('compras', '0002_auto_20200413_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la compra')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('fecha_c', models.DateField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('fecha_a', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
                ('documento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Documento de referencia')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuestos.Articulos', verbose_name='Articulo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedores', verbose_name='Proveedor')),
            ],
        ),
    ]
