# Generated by Django 3.0.4 on 2020-04-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='tipo',
            field=models.TextField(blank=True, choices=[('Normal', 'Normal')], null=True, verbose_name='Tipo'),
        ),
    ]
