# Generated by Django 3.0.4 on 2020-04-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compras_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ANT', 'Anticipada'), ('NORMAL', 'Normal')], max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
