# Generated by Django 3.0.4 on 2020-04-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('compras', '0005_auto_20200415_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyectos'),
        ),
    ]
