# Generated by Django 3.0.4 on 2020-06-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_compras_precio_presup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Monto de la compra')),
                ('estado', models.CharField(blank=True, choices=[('ESPERA', 'Espera'), ('AUTORIZADA', 'Autorizada'), ('NO AUTORIZADA', 'No Autorizada')], max_length=20, null=True, verbose_name='Estado')),
                ('adjunto', models.ImageField(upload_to='', verbose_name='Imagen adjunta')),
                ('fecha_c', models.DateField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedores', verbose_name='Nombre del contratista')),
            ],
            options={
                'verbose_name': 'Comparativa',
                'verbose_name_plural': 'Comparativas',
            },
        ),
    ]
