# Generated by Django 3.0.4 on 2020-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_comparativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='comparativas',
            name='proyecto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='comparativas',
            name='estado',
            field=models.CharField(blank=True, choices=[('ESPERA', 'Espera'), ('AUTORIZADA', 'Autorizada'), ('NO AUTORIZADA', 'No Autorizada')], default='ESPERA', editable=False, max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
