# Generated by Django 3.0.4 on 2020-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_auto_20200618_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='imprevisto',
            field=models.CharField(blank=True, choices=[('IMPREVISTO', 'Imprevisto'), ('PREVISTO', 'Previsto')], max_length=200, null=True, verbose_name='Imprevisto'),
        ),
        migrations.AddField(
            model_name='compras',
            name='partida',
            field=models.FloatField(blank=True, null=True, verbose_name='Partida'),
        ),
    ]
