# Generated by Django 3.0.4 on 2020-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_auto_20200623_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='comentario',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Comentario'),
        ),
    ]
