# Generated by Django 3.0.4 on 2020-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_comparativas_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='adj_oc',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Orden de compra'),
        ),
        migrations.AddField(
            model_name='comparativas',
            name='o_c',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº orden de compra'),
        ),
        migrations.AlterField(
            model_name='comparativas',
            name='estado',
            field=models.CharField(blank=True, choices=[('ESPERA', 'Espera'), ('AUTORIZADA', 'Autorizada'), ('NO AUTORIZADA', 'No Autorizada'), ('ADJUNTO ✓', 'Adj Autorizada')], default='ESPERA', editable=False, max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
