# Generated by Django 3.0.4 on 2020-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_auto_20200911_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='fecha_autorizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de aturorizacion'),
        ),
    ]
