# Generated by Django 3.0.4 on 2020-10-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_auto_20201029_1219'),
        ('compras', '0016_comparativas_visto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativasMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mensaje')),
                ('comparativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Comparativas', verbose_name='Comparativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
