# Generated by Django 3.0.4 on 2020-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_comparativasmensaje_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='creador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Crador'),
        ),
    ]
