# Generated by Django 3.0.4 on 2020-12-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_comparativas_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='estado',
            field=models.CharField(blank=True, choices=[('ESPERA', 'Espera'), ('CHEQUEADO', 'Chequeado')], default='ESPERA', max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='contrato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Contratos', verbose_name='Contrato'),
        ),
    ]
