# Generated by Django 3.0.4 on 2021-05-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_auto_20201215_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntosContratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('adjunto', models.FileField(upload_to='', verbose_name='Archivo')),
                ('fecha_c', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Adjunto de contratos',
                'verbose_name_plural': 'Adjuntos de contratos',
            },
        ),
        migrations.AddField(
            model_name='comparativas',
            name='autoriza',
            field=models.CharField(blank=True, choices=[('PL', 'Pl'), ('SP', 'Sp')], max_length=20, null=True, verbose_name='Autoriza'),
        ),
        migrations.AddField(
            model_name='comparativas',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Contratos', verbose_name='Vincala a un contrato'),
        ),
        migrations.AddField(
            model_name='comparativas',
            name='publica',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=20, null=True, verbose_name='Es publica?'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='actualiza',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Como actualiza'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='monto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto final'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='np',
            field=models.CharField(max_length=200, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedores', verbose_name='Proveedor'),
        ),
    ]
