# Generated by Django 3.0.4 on 2021-05-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_auto_20210527_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntoscontratos',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Contratos', verbose_name='Vincala a un contrato'),
        ),
    ]
