# Generated by Django 3.2.5 on 2021-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_adjuntoscontratos_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='tipo_oc',
            field=models.CharField(blank=True, choices=[('MATERIALES', 'Materiales'), ('SERVICIOS', 'Servicios'), ('CONTRATOS', 'Contratos')], max_length=40, null=True, verbose_name='Tipo de OC'),
        ),
    ]
