# Generated by Django 3.2.5 on 2021-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0049_arqueochanchito'),
        ('compras', '0024_comparativas_tipo_oc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoOrdenesCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField()),
                ('usuarios', models.ManyToManyField(to='rrhh.datosusuario')),
            ],
            options={
                'verbose_name': 'Aviso de ordenes de compra',
                'verbose_name_plural': 'Avisos de ordenes de compra',
            },
        ),
    ]
