# Generated by Django 3.2.5 on 2021-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0025_avisoordenescompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='visto_gerente',
            field=models.BooleanField(default=False, verbose_name='Visto del gerente'),
        ),
    ]
