# Generated by Django 3.2.5 on 2021-09-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0031_documentacionproyectopresupuesto'),
        ('compras', '0027_comparativas_visto_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='capitulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuestos.capitulos'),
        ),
    ]
