# Generated by Django 3.2.5 on 2021-11-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0032_auto_20211124_1450'),
        ('compras', '0031_alter_proveedores_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo', to='presupuestos.articulos', verbose_name='Articulo'),
        ),
    ]
