# Generated by Django 3.2.5 on 2022-02-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0057_datosusuario_user'),
        ('compras', '0032_alter_compras_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='gerente_autoriza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.datosusuario', verbose_name='Gerente que autoriza'),
        ),
    ]
