# Generated by Django 3.2.5 on 2022-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0033_comparativas_gerente_autoriza'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparativas',
            name='quien_autorizo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Quien autorizo'),
        ),
    ]
