# Generated by Django 3.0.4 on 2020-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConstantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constante', models.CharField(max_length=200)),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Registro de contantes',
                'verbose_name_plural': 'Registros de constantes',
            },
        ),
    ]
