# Generated by Django 3.0.4 on 2020-05-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200420_1150'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroValorProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha que corresponde')),
                ('precio_proyecto', models.FloatField(verbose_name='Precio del proyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Registro de precios de proyecto',
                'verbose_name_plural': 'Registro de precios de proyectos',
            },
        ),
    ]
