# Generated by Django 3.0.4 on 2020-05-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_registroleccionesaprendidaspresup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroleccionesaprendidaspresup',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo'),
        ),
    ]
